import { DocumentConfig, FieldMeta } from "./types";

const PARTY_FIELDS: FieldMeta[] = [
  { key: "printName", label: "Print Name", kind: "text" },
  { key: "title", label: "Title", kind: "text" },
  { key: "company", label: "Company", kind: "text" },
  { key: "noticeAddress", label: "Notice Address", kind: "text" },
  { key: "date", label: "Date", kind: "text" },
];

function party(key: string, label: string, linkNames?: string[]): FieldMeta {
  return { key, label, kind: "group", fields: PARTY_FIELDS, isParty: true, linkNames: linkNames ?? [label] };
}

export const DOCUMENT_CONFIGS: DocumentConfig[] = [
  {
    slug: "mutual_nda",
    displayName: "Mutual Non-Disclosure Agreement",
    templateFilename: "Mutual-NDA.md",
    fields: [
      { key: "purpose", label: "Purpose", kind: "long_text", linkNames: ["Purpose"], summarize: true },
      { key: "effectiveDate", label: "Effective Date", kind: "date", linkNames: ["Effective Date"], summarize: true },
      { key: "mndaTerm", label: "MNDA Term", kind: "enum", linkNames: ["MNDA Term"], summarize: true },
      { key: "mndaTermYears", label: "MNDA Term (years)", kind: "integer" },
      { key: "termOfConfidentiality", label: "Term of Confidentiality", kind: "enum", linkNames: ["Term of Confidentiality"], summarize: true },
      { key: "termOfConfidentialityYears", label: "Term of Confidentiality (years)", kind: "integer" },
      { key: "governingLaw", label: "Governing Law", kind: "text", linkNames: ["Governing Law"], summarize: true },
      { key: "jurisdiction", label: "Jurisdiction", kind: "text", linkNames: ["Jurisdiction"], summarize: true },
      { key: "modifications", label: "MNDA Modifications", kind: "long_text", summarize: true },
      party("partyOne", "Party 1"),
      party("partyTwo", "Party 2"),
    ],
  },
  {
    slug: "pilot_agreement",
    displayName: "Pilot Agreement",
    templateFilename: "Pilot-Agreement.md",
    fields: [
      { key: "effectiveDate", label: "Effective Date", kind: "date", linkNames: ["Effective Date"], summarize: true },
      { key: "pilotPeriod", label: "Pilot Period", kind: "text", linkNames: ["Pilot Period"], summarize: true },
      { key: "generalCapAmount", label: "General Cap Amount", kind: "text", linkNames: ["General Cap Amount"], summarize: true },
      { key: "governingLaw", label: "Governing Law", kind: "text", linkNames: ["Governing Law"], summarize: true },
      { key: "chosenCourts", label: "Chosen Courts", kind: "text", linkNames: ["Chosen Courts"], summarize: true },
      party("provider", "Provider"),
      party("customer", "Customer"),
    ],
  },
  {
    slug: "csa",
    displayName: "Cloud Service Agreement",
    templateFilename: "CSA.md",
    fields: [
      { key: "subscriptionPeriod", label: "Subscription Period", kind: "text", linkNames: ["Subscription Period"], summarize: true },
      { key: "technicalSupport", label: "Technical Support", kind: "text", linkNames: ["Technical Support"] },
      { key: "useLimitations", label: "Use Limitations", kind: "long_text", linkNames: ["Use Limitations"] },
      { key: "paymentProcess", label: "Payment Process", kind: "text", linkNames: ["Payment Process"], summarize: true },
      { key: "orderDate", label: "Order Date", kind: "date", linkNames: ["Order Date"] },
      { key: "nonRenewalNoticeDate", label: "Non-Renewal Notice Date", kind: "text", linkNames: ["Non-Renewal Notice Date"] },
      { key: "effectiveDate", label: "Effective Date", kind: "date", linkNames: ["Effective Date"], summarize: true },
      { key: "additionalWarranties", label: "Additional Warranties", kind: "long_text", linkNames: ["Additional Warranties"] },
      { key: "generalCapAmount", label: "General Cap Amount", kind: "text", linkNames: ["General Cap Amount"], summarize: true },
      { key: "increasedClaims", label: "Increased Claims", kind: "long_text", linkNames: ["Increased Claims"] },
      { key: "increasedCapAmount", label: "Increased Cap Amount", kind: "text", linkNames: ["Increased Cap Amount"] },
      { key: "unlimitedClaims", label: "Unlimited Claims", kind: "long_text", linkNames: ["Unlimited Claims"] },
      { key: "providerCoveredClaims", label: "Provider Covered Claims", kind: "long_text", linkNames: ["Provider Covered Claims", "Provider Covered Claim"] },
      { key: "customerCoveredClaims", label: "Customer Covered Claims", kind: "long_text", linkNames: ["Customer Covered Claims", "Customer Covered Claim"] },
      { key: "governingLaw", label: "Governing Law", kind: "text", linkNames: ["Governing Law"], summarize: true },
      { key: "chosenCourts", label: "Chosen Courts", kind: "text", linkNames: ["Chosen Courts"], summarize: true },
      party("provider", "Provider"),
      party("customer", "Customer"),
    ],
  },
  {
    slug: "sla",
    displayName: "Service Level Agreement",
    templateFilename: "sla.md",
    fields: [
      { key: "targetUptime", label: "Target Uptime", kind: "text", linkNames: ["Target Uptime"], summarize: true },
      { key: "targetResponseTime", label: "Target Response Time", kind: "text", linkNames: ["Target Response Time"], summarize: true },
      { key: "supportChannel", label: "Support Channel", kind: "text", linkNames: ["Support Channel"] },
      { key: "uptimeCredit", label: "Uptime Credit", kind: "text", linkNames: ["Uptime Credit"] },
      { key: "responseTimeCredit", label: "Response Time Credit", kind: "text", linkNames: ["Response Time Credit"] },
      { key: "scheduledDowntime", label: "Scheduled Downtime", kind: "text", linkNames: ["Scheduled Downtime"] },
      { key: "subscriptionPeriod", label: "Subscription Period", kind: "text", linkNames: ["Subscription Period"], summarize: true },
      party("provider", "Provider"),
      party("customer", "Customer"),
    ],
  },
  {
    slug: "psa",
    displayName: "Professional Services Agreement",
    templateFilename: "psa.md",
    fields: [
      { key: "effectiveDate", label: "Effective Date", kind: "date", linkNames: ["Effective Date"], summarize: true },
      { key: "customerPolicies", label: "Customer Policies", kind: "long_text", linkNames: ["Customer Policies"] },
      { key: "securityPolicy", label: "Security Policy", kind: "text", linkNames: ["Security Policy"] },
      { key: "additionalWarranties", label: "Additional Warranties", kind: "long_text", linkNames: ["Additional Warranties"] },
      { key: "generalCapAmount", label: "General Cap Amount", kind: "text", linkNames: ["General Cap Amount"], summarize: true },
      { key: "increasedClaims", label: "Increased Claims", kind: "long_text", linkNames: ["Increased Claims"] },
      { key: "increasedCapAmount", label: "Increased Cap Amount", kind: "text", linkNames: ["Increased Cap Amount"] },
      { key: "unlimitedClaims", label: "Unlimited Claims", kind: "long_text", linkNames: ["Unlimited Claims"] },
      { key: "insuranceMinimums", label: "Insurance Minimums", kind: "text", linkNames: ["Insurance Minimums"] },
      { key: "providerCoveredClaims", label: "Provider Covered Claims", kind: "long_text", linkNames: ["Provider Covered Claims", "Provider Covered Claim"] },
      { key: "customerCoveredClaims", label: "Customer Covered Claims", kind: "long_text", linkNames: ["Customer Covered Claims", "Customer Covered Claim"] },
      { key: "governingLaw", label: "Governing Law", kind: "text", linkNames: ["Governing Law"], summarize: true },
      { key: "chosenCourts", label: "Chosen Courts", kind: "text", linkNames: ["Chosen Courts"], summarize: true },
      {
        key: "sows",
        label: "Statements of Work",
        kind: "group",
        repeat: true,
        appendixTitle: "Statements of Work",
        fields: [
          { key: "sowId", label: "SOW label", kind: "text" },
          { key: "title", label: "Title", kind: "text" },
          { key: "deliverables", label: "Deliverables", kind: "long_text" },
          { key: "fees", label: "Fees", kind: "text" },
          { key: "paymentPeriod", label: "Payment Period", kind: "text" },
          { key: "sowTerm", label: "SOW Term", kind: "text" },
          { key: "rejectionPeriod", label: "Rejection Period", kind: "text" },
          { key: "resubmissionPeriod", label: "Resubmission Period", kind: "text" },
          { key: "timeOfAssignment", label: "Time of Assignment", kind: "text" },
          { key: "customerObligations", label: "Customer Obligations", kind: "long_text" },
        ],
      },
      party("provider", "Provider"),
      party("customer", "Customer"),
    ],
  },
  {
    slug: "software_license",
    displayName: "Software License Agreement",
    templateFilename: "Software-License-Agreement.md",
    fields: [
      { key: "subscriptionPeriod", label: "Subscription Period", kind: "text", linkNames: ["Subscription Period"], summarize: true },
      { key: "permittedUses", label: "Permitted Uses", kind: "long_text", linkNames: ["Permitted Uses"], summarize: true },
      { key: "licenseLimits", label: "License Limits", kind: "long_text", linkNames: ["License Limits"] },
      { key: "paymentProcess", label: "Payment Process", kind: "text", linkNames: ["Payment Process"], summarize: true },
      { key: "orderDate", label: "Order Date", kind: "date", linkNames: ["Order Date"] },
      { key: "nonRenewalNoticeDate", label: "Non-Renewal Notice Date", kind: "text", linkNames: ["Non-Renewal Notice Date"] },
      { key: "warrantyPeriod", label: "Warranty Period", kind: "text", linkNames: ["Warranty Period"] },
      { key: "deletionProcedure", label: "Deletion Procedure", kind: "text", linkNames: ["Deletion Procedure"] },
      { key: "effectiveDate", label: "Effective Date", kind: "date", linkNames: ["Effective Date"], summarize: true },
      { key: "additionalWarranties", label: "Additional Warranties", kind: "long_text", linkNames: ["Additional Warranties"] },
      { key: "generalCapAmount", label: "General Cap Amount", kind: "text", linkNames: ["General Cap Amount"], summarize: true },
      { key: "increasedClaims", label: "Increased Claims", kind: "long_text", linkNames: ["Increased Claims"] },
      { key: "increasedCapAmount", label: "Increased Cap Amount", kind: "text", linkNames: ["Increased Cap Amount"] },
      { key: "unlimitedClaims", label: "Unlimited Claims", kind: "long_text", linkNames: ["Unlimited Claims"] },
      { key: "providerCoveredClaims", label: "Provider Covered Claims", kind: "long_text", linkNames: ["Provider Covered Claims", "Provider Covered Claim"] },
      { key: "customerCoveredClaims", label: "Customer Covered Claims", kind: "long_text", linkNames: ["Customer Covered Claims", "Customer Covered Claim"] },
      { key: "governingLaw", label: "Governing Law", kind: "text", linkNames: ["Governing Law"], summarize: true },
      { key: "chosenCourts", label: "Chosen Courts", kind: "text", linkNames: ["Chosen Courts"], summarize: true },
      party("provider", "Provider"),
      party("customer", "Customer"),
    ],
  },
  {
    slug: "partnership_agreement",
    displayName: "Partnership Agreement",
    templateFilename: "Partnership-Agreement.md",
    fields: [
      { key: "obligations", label: "Obligations", kind: "long_text", linkNames: ["Obligations"], summarize: true },
      { key: "paymentProcess", label: "Payment Process", kind: "text", linkNames: ["Payment Process"] },
      { key: "paymentSchedule", label: "Payment Schedule", kind: "text", linkNames: ["Payment Schedule"] },
      { key: "territory", label: "Territory", kind: "text", linkNames: ["Territory"] },
      { key: "endDate", label: "End Date", kind: "date", linkNames: ["End Date"], summarize: true },
      { key: "effectiveDate", label: "Effective Date", kind: "date", linkNames: ["Effective Date"], summarize: true },
      { key: "additionalWarranties", label: "Additional Warranties", kind: "long_text", linkNames: ["Additional Warranties"] },
      { key: "generalCapAmount", label: "General Cap Amount", kind: "text", linkNames: ["General Cap Amount"], summarize: true },
      { key: "increasedClaims", label: "Increased Claims", kind: "long_text", linkNames: ["Increased Claims"] },
      { key: "increasedCapAmount", label: "Increased Cap Amount", kind: "text", linkNames: ["Increased Cap Amount"] },
      { key: "unlimitedClaims", label: "Unlimited Claims", kind: "long_text", linkNames: ["Unlimited Claims"] },
      { key: "companyCoveredClaims", label: "Company Covered Claims", kind: "long_text", linkNames: ["Company Covered Claim", "Company Covered Claims"] },
      { key: "partnerCoveredClaims", label: "Partner Covered Claims", kind: "long_text", linkNames: ["Partner Covered Claims", "Partner Covered Claim"] },
      { key: "governingLaw", label: "Governing Law", kind: "text", linkNames: ["Governing Law"], summarize: true },
      { key: "chosenCourts", label: "Chosen Courts", kind: "text", linkNames: ["Chosen Courts"], summarize: true },
      {
        key: "trademarkGrantor",
        label: "Trademark Grantor (Licensor)",
        kind: "enum",
        summarize: true,
      },
      party("company", "Company"),
      party("partner", "Partner"),
    ],
  },
  {
    slug: "dpa",
    displayName: "Data Processing Agreement",
    templateFilename: "DPA.md",
    fields: [
      { key: "customerProcessingRole", label: "Customer's Data Protection Role", kind: "enum", summarize: true },
      { key: "categoriesOfPersonalData", label: "Categories of Personal Data", kind: "long_text", linkNames: ["Categories of Personal Data"], summarize: true },
      { key: "categoriesOfDataSubjects", label: "Categories of Data Subjects", kind: "long_text", linkNames: ["Categories of Data Subjects"], summarize: true },
      { key: "specialCategoryData", label: "Special Category Data", kind: "long_text", linkNames: ["Special Category Data"] },
      { key: "specialCategoryDataSafeguards", label: "Special Category Data Restrictions or Safeguards", kind: "long_text", linkNames: ["Special Category Data Restrictions or Safeguards"] },
      { key: "frequencyOfTransfer", label: "Frequency of Transfer", kind: "text", linkNames: ["Frequency of Transfer"] },
      { key: "natureAndPurposeOfProcessing", label: "Nature and Purpose of Processing", kind: "long_text", linkNames: ["Nature and Purpose of Processing"], summarize: true },
      { key: "durationOfProcessing", label: "Duration of Processing", kind: "text", linkNames: ["Duration of Processing"], summarize: true },
      { key: "governingMemberState", label: "Governing Member State", kind: "text", linkNames: ["Governing Member State"] },
      { key: "providerSecurityContact", label: "Provider Security Contact", kind: "text", linkNames: ["Provider Security Contact"] },
      {
        key: "approvedSubprocessors",
        label: "Approved Subprocessors",
        kind: "group",
        repeat: true,
        appendixTitle: "Approved Subprocessors",
        fields: [
          { key: "name", label: "Name", kind: "text" },
          { key: "country", label: "Country", kind: "text" },
          { key: "processingTasks", label: "Anticipated Processing Tasks", kind: "text" },
        ],
      },
      party("provider", "Provider"),
      party("customer", "Customer"),
    ],
  },
  {
    slug: "baa",
    displayName: "Business Associate Agreement",
    templateFilename: "BAA.md",
    fields: [
      { key: "limitations", label: "Limitations", kind: "long_text", linkNames: ["Limitations"] },
      { key: "breachNotificationPeriod", label: "Breach Notification Period", kind: "text", linkNames: ["Breach Notification Period"], summarize: true },
      { key: "baaEffectiveDate", label: "BAA Effective Date", kind: "date", linkNames: ["BAA Effective Date"], summarize: true },
      party("provider", "Provider"),
      party("company", "Company"),
    ],
  },
  {
    slug: "ai_addendum",
    displayName: "AI Addendum",
    templateFilename: "AI-Addendum.md",
    fields: [
      { key: "trainingData", label: "Training Data", kind: "long_text", linkNames: ["Training Data"], summarize: true },
      { key: "trainingPurposes", label: "Training Purposes", kind: "long_text", linkNames: ["Training Purposes"] },
      { key: "trainingRestrictions", label: "Training Restrictions", kind: "long_text", linkNames: ["Training Restrictions"] },
      { key: "improvementRestrictions", label: "Improvement Restrictions", kind: "long_text", linkNames: ["Improvement Restrictions"] },
      party("customer", "Customer"),
      party("provider", "Provider"),
    ],
  },
  {
    slug: "design_partner_agreement",
    displayName: "Design Partner Agreement",
    templateFilename: "design-partner-agreement.md",
    fields: [
      { key: "program", label: "Program", kind: "long_text", linkNames: ["Program"], summarize: true },
      { key: "term", label: "Term", kind: "text", linkNames: ["Term"], summarize: true },
      { key: "fees", label: "Fees", kind: "text", linkNames: ["Fees"] },
      { key: "effectiveDate", label: "Effective Date", kind: "date", linkNames: ["Effective Date"], summarize: true },
      { key: "governingLaw", label: "Governing Law", kind: "text", linkNames: ["Governing Law"], summarize: true },
      { key: "chosenCourts", label: "Chosen Courts", kind: "text", linkNames: ["Chosen Courts"], summarize: true },
      party("provider", "Provider"),
      party("partner", "Partner"),
    ],
  },
];

export const DOCUMENT_CONFIG_BY_SLUG: Record<string, DocumentConfig> = Object.fromEntries(
  DOCUMENT_CONFIGS.map((config) => [config.slug, config]),
);
